config/routes.rb
Rails.application.routes.draw do
  resources :quotes
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "quotes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/quote.rb
class Quote < ApplicationRecord
    validates :name, presence: true
    scope :ordered, -> { order(id: :desc) }

    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: %i[ show edit update destroy ]

  # GET /quotes or /quotes.json
  def index
    @quotes = Quote.ordered
  end

  # GET /quotes/1 or /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes or /quotes.json
  def create
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to quote_url(@quote), notice: "Quote was successfully created." }
        format.turbo_stream
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1 or /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        respond_to do |format|
          format.html { redirect_to quotes_path, notice: "Quote was successfully updated." }
          format.turbo_stream { flash.now[:notice] = "Quote was successfully updated." }
        end
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1 or /quotes/1.json
  def destroy
    @quote.destroy

    respond_to do |format|
      format.html { redirect_to quotes_path, notice: "Quote was successfully destroyed." }
      format.turbo_stream
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def quote_params
      params.require(:quote).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def render_turbo_stream_flash_messages
        turbo_stream.prepend "flash", partial: "shared/flash"
    end
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YdevisApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/quotes/_form.html.erb
<%# app/views/quotes/_form.html.erb %>

<%= simple_form_for quote, html: { class: "quote form" } do |f| %>
  <% if quote.errors.any? %>
    <div class="error-message">
      <%= quote.errors.full_messages.to_sentence.capitalize %>
    </div>
  <% end %>

  <%= f.input :name, input_html: { autofocus: true } %>
  <%= link_to "Cancel", quotes_path, class: "btn btn--light" %>
  <%= f.submit class: "btn btn--secondary" %>
<% end %>

app/views/quotes/_quote.html.erb
<%# app/views/quotes/_quote.html.erb %>

<%= turbo_frame_tag quote do %>
    <div class="quote">
        <%= link_to quote.name, quote_path(quote),
        data:{turbo_frame: "_top"} %>
        <div class="quote__actions">
            <%= button_to "Supprimer",
                    quote_path(quote),
                    method: :delete,
                    class: "btn btn--light" %>
            <%= link_to "Modifier",
                  edit_quote_path(quote),
                  class: "btn btn--light" %>
        </div>
    </div>
<% end %>

app/views/quotes/create.turbo_stream.erb
<%# app/views/quotes/create.turbo_stream.erb %>

<%= turbo_stream.prepend "quotes" do %>
  <%= render @quote %>
<% end %>

<%= turbo_stream.update Quote.new, "" %>

<%= turbo_stream.prepend "quotes", @quote %>
<%= turbo_stream.update Quote.new, "" %>




<%# app/views/quotes/create.turbo_stream.erb %>

<%#= turbo_stream.prepend "quotes", partial: "quotes/quote", locals: { quote: @quote } %>
<%#= turbo_stream.update Quote.new, "" %>
<%# While this is a perfectly valid way of writing our view, there is another syntax with a
 block I sometimes use when lines are too long: %>
 
<%# app/views/quotes/create.turbo_stream.erb %>

<%#= turbo_stream.prepend "quotes" do %>
  <%#= render partial: "quotes/quote", locals: { quote: @quote } %>
<%# end %>

<%#= turbo_stream.update Quote.new, "" %>

<%# In Ruby on Rails, the following two expressions are equivalent: %>

<%#=  render partial: "quotes/quote", locals: { quote: @quote } %>
<%#= render @quote %>

app/views/quotes/destroy.turbo_stream.erb
<%# app/views/quotes/destroy.turbo_stream.erb %>

<%= turbo_stream.remove @quote %>

app/views/quotes/edit.html.erb
<%# app/views/quotes/edit.html.erb %>

<main class="container">
    <%= link_to sanitize("&larr; Back to quote"), quote_path(@quote) %>

    <div class="header">
        <h1>Edit quote</h1>
    </div>

    <%= turbo_frame_tag "quote_#{@quote.id}" do %>
      <%= render "form", quote: @quote %>
    <% end %>
</main>

app/views/quotes/index.html.erb
<%# app/views/quotes/index.html.erb %>

<div class="container">
  <div class="header">
    <h1>Quotes</h1>
    <%= link_to "New quote",
                new_quote_path,
                class: "btn btn--primary",
                data: { turbo_frame: dom_id(Quote.new) } %>
  </div>

  <%= turbo_frame_tag Quote.new %>

  <%= turbo_frame_tag "quotes" do %>
    <%= render @quotes %>
  <% end %>
</div>

app/views/quotes/new.html.erb
<%# app/views/quotes/new.html.erb %>

<main class="container">
    
    <%= link_to sanitize("&larr; Back to quotes"), quotes_path %>

    <div class="header">
        <h1>New quote</h1>
    </div>
    <%= turbo_frame_tag @quote do %>
    <%= render "form", quote: @quote %>
    <% end %>
    
</main>

app/views/quotes/show.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to quotes"), quotes_path %>
  <div class="header">
    <h1>
      <%= @quote.name %>
    </h1>
  </div>
</main>

app/views/quotes/update.turbo_stream.erb
<%# app/views/quotes/destroy.turbo_stream.erb %>

<%= turbo_stream.replace @quote %>
<%= render_turbo_stream_flash_messages %>